// Prueba opcional de la interfaz real. Requiere Playwright y Chromium solo en desarrollo.
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');
const { pathToFileURL } = require('node:url');
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, acceptDownloads: true });
  const page = await context.newPage();
  const errors = [], externalRequests = [];
  page.on('pageerror', e => errors.push(e.message));
  await context.route(/^https?:/, route => { externalRequests.push(route.request().url()); return route.abort(); });
  const url = pathToFileURL(path.resolve(__dirname, '../index.html')).href;
  await page.goto(url);
  await page.locator('#exercise-form button[type=submit]').click();
  assert.match(await page.locator('#stats').innerText(), /11/);
  assert.match(await page.locator('#stats').innerText(), /26\.67/);
  await page.locator('#last').click();
  assert.match(await page.locator('#detail-title').innerText(), /15/);
  assert.equal(await page.locator('#event-state .frame-card').count(), 4);
  await page.locator('#first').click();
  assert.match(await page.locator('#detail-title').innerText(), /Antes/);
  await page.locator('#progressive').check();
  assert.equal(await page.locator('#matrix thead th').count(), 2);
  await page.locator('#next').click();
  assert.equal(await page.locator('#matrix thead th').count(), 3);
  await page.locator('#progressive').uncheck();
  await page.selectOption('#example', 'clock');
  assert.match(await page.locator('#stats').innerText(), /16\.67/);
  await page.locator('[data-step="7"]').click();
  assert.equal(await page.locator('.event-list button').count(), 11);
  await page.locator('[data-event="2"]').click();
  assert.match(await page.locator('#event-state').innerText(), /intermedio/i);
  await page.locator('#compare').click();
  assert.equal(await page.locator('#comparison tbody tr').count(), 6);
  await page.locator('[data-algorithm="LRU"]').click();
  assert.equal(await page.locator('#algorithm').inputValue(), 'LRU');
  await page.fill('#references', '1 nope!');
  assert.ok(await page.locator('#compare').isDisabled());
  await page.locator('#exercise-form button[type=submit]').click();
  assert.ok(await page.locator('#error').isVisible());
  await page.selectOption('#example', 'nru');
  assert.ok(await page.locator('#nru-options').isVisible());
  assert.ok(await page.locator('#error').isHidden());
  const beforeStats = await page.locator('#stats').innerText();
  const downloadPromise=page.waitForEvent('download');
  await page.locator('#save').click();
  const download=await downloadPromise;
  const saved=await fs.readFile(await download.path(), 'utf8');
  assert.equal(JSON.parse(saved).config.algorithm,'NRU');
  await page.selectOption('#example', 'fifo4');
  await page.locator('#file').setInputFiles({name:'ejercicio.json', mimeType:'application/json',buffer:Buffer.from(saved)});
  await page.waitForFunction(()=>document.getElementById('algorithm').value==='NRU');
  assert.equal(await page.locator('#stats').innerText(),beforeStats);
  await page.locator('#file').setInputFiles({name:'error.json',mimeType:'application/json',buffer:Buffer.from('{"format":"mmu-exercise","version":1,"config":{}}')});
  await page.waitForFunction(()=>!document.getElementById('error').hidden);
  assert.match(await page.locator('#error').innerText(),/No se pudo abrir/);
  await page.selectOption('#example', 'long');
  assert.equal(await page.locator('#matrix thead th').count(), 42);
  await page.evaluate(()=>{window.print=()=>{window.printed=true;};});
  await page.locator('#print').click();
  assert.ok(await page.evaluate(()=>window.printed));
  assert.equal(await page.locator('#print-area .print-block').count(), 4);
  assert.equal(await page.locator('#print-area .matrix thead th:not(:first-child)').count(),40);
  await page.locator('#last').click();
  const lastPosition=await page.locator('#position').innerText();
  assert.match(lastPosition,/40 \/ 40/);
  await page.reload();
  assert.equal(await page.locator('#references').inputValue().then(x=>x.split(',').length),40);
  await page.selectOption('#example','fifo4');
  await page.locator('[data-step="5"]').click();
  const output=process.env.MMU_SCREENSHOT_DIR;
  if(output) { await fs.mkdir(output,{recursive:true}); await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true}); }
  await page.setViewportSize({width:390,height:844});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
  assert.equal(overflow,false,'La página móvil no debe desbordarse; solo la matriz tiene scroll.');
  if(output) await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
  assert.deepEqual(errors,[]); assert.deepEqual(externalRequests,[]);
  console.log('Interfaz OK: file:// sin red, ejemplos, navegación, estados intermedios, comparación, errores, JSON, impresión, borrador y móvil.');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
